spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fypweb
    username: root
    password: Speedy_02
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    async:
      request-timeout: 60000  # 60 seconds
httpclient:
  read-timeout: 60000  # 60 seconds
  connect-timeout: 60000  # 60 seconds
server:
  tomcat:
    connection-timeout: 60000  # 60 seconds